### ISSUE TITLE
Rename suffix to file extension, allow multiple

### ISSUE THREAD

**Issue by bmarwell** [java-native/libloader#3]
E.g.
`.dylib` and `.jnilib` on Mac.

* On Darwin, the default mapping is to `.jnilib`; but we use `.dylib`s so that library interdependencies are  handled correctly. if we don't find a `.dylib`, try `.jnilib` instead.

> JNI libraries are named with the library name used in the System.loadLibrary() method of your Java code, prefixed by lib and suffixed with .jnilib. For example, System.loadLibrary("hello") loads the library named libhello.jnilib. Java HotSpot also recognizes .dylib as a valid JNI library format as of OS X v10.5.

Source: https://developer.apple.com/library/archive/documentation/Java/Conceptual/Java14Development/05-CoreJavaAPIs/CoreJavaAPIs.html

[According to this site](https://adamish.com/blog/archives/620), `.jnilib` is regarded the older extension but should still work.

**Comment by tresf** [comment]
I think they're both acceptable, unless [you're on Java 6](https://github.com/virtuoushub/lwjgl3/commit/4f5a9f721afda74f74e4eeb5e395f9d44b7a0f63#diff-f1335d009d4ad2058cb88d129d5be773R506), no?

**Comment by bmarwell** [comment]
Even if you are on java 6, both are acceptable as this library loader can only use `.load()` instead of `.loadLibrary()`.

I need to document this a little better. This issue could only serve as a reminder to me so far
